[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=d214b3e1-a4d4-4227-8bf8-d0d581c67424
Description=关卡01
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
'==========以下是按键精灵录制的内容==========
MoveTo 820, 353
Delay 200
LeftDown 1
MoveTo 820, 757
Delay 200
LeftUp 1
'==========以上是按键精灵录制的内容==========
